# docker-compose -f my-compose-file.yml up
services:
  asbe:
    image: asbe
    ports:
      - 9111:8080
    build:
      context: .
      dockerfile: asbe/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - PgDev=${PgDev}
      
  ng-bidstur:
    image: ng-bidstur
    ports:
      - 9112:80
    build:
      context: .
      dockerfile: ng-bidstur/Dockerfile
