# docker-compose -f my-compose-file.yml up
services:
  asbe:
    image: asbe
    ports:
      - 9001:8080
    build:
      context: .
      dockerfile: asbe/Dockerfile
      
  ng-bidstur:
    image: ng-bidstur
    ports:
      - 9002:80
    build:
      context: .
      dockerfile: ng-bidstur/Dockerfile
